name: Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir output
          pandoc README.md -f markdown -t html -s -H style.css -o output/index.html

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-blog
          path: output/index.html
